aws_instance = "t2.micro"
backend_ami = "ami-002070d43b0a4f171"
frontend_ami = "ami-0729e439b6769d6ab"
mariadb_user_data = "mariadb.tpl"
memcahed_user_data = "memcached.sh"
my_key_location = "terraform-key.pub"
rabbitmq_user_data = "rabbitmq.sh"
tomcat_user_data = "webapp.sh"